### ISSUE TITLE
undefined function mime_content_type()

### ISSUE THREAD

**Issue by poblabs** [HaschekSolutions/opentrashmail#1]
This is a fun project, thanks for creating it! Today when I was playing around with it in a Docker container, I used Outlook to send an attachment of a screenshot saved in JPG, and when I received the email in opentrashmail, I get the subject and body. When I click on the attachment link I received: 

```
Fatal error: Uncaught Error: Call to undefined function mime_content_type() in /var/www/opentrashmail/web/api.php:34 Stack trace: #0 {main} thrown in /var/www/opentrashmail/web/api.php on line 34
```

I'm not sure how else to help, my docker troubleshooting skills aren't the best. Let me know how I can assist.

**Comment by chrisiaut** [comment]
Thanks! new docker image is building and should be available in a few minutes
