### ISSUE TITLE
Docker for ARM 

### ISSUE THREAD

**Issue by gwenvador** [HaschekSolutions/opentrashmail#12]
Have you build a docker for ARM? I am interested to use opentrashmail on raspberrypi.

**Comment by geek-at** [comment]
Interesting thought. I'm not sure the python library will run on ARM but I'll test and add a image if I can make it work

**Comment by DLArts** [comment]
It works flawless on a Raspberry Pi 4 running DietPi.
Just checkout the repository, switch into the directory "docker" and run
`docker build -t hascheksolutions/opentrashmail .`
