### ISSUE TITLE
README Improvements

### ISSUE THREAD

**Issue by mattburchett** [HaschekSolutions/opentrashmail#16]
Hey there! 

I was looking over your project and setting it up to use it myself. As I was going through the README, I noticed a handful of spelling and grammar errors. 

Would you have an interest in me submitting a PR to fix those? They're already up on my branch [here](https://github.com/mattburchett/opentrashmail/tree/fix/README).

**Comment by geek-at** [comment]
sure, much appreciated

**Comment by mattburchett** [comment]
I opened #17.
