### ISSUE TITLE
mailfrom.endswith block all 

### ISSUE THREAD

**Issue by aagarop** [HaschekSolutions/opentrashmail#18]
Hi
I have a problem with blocking emails that do not come from a specific domain.
The mailfrom.endswith element works independently in test but in the server all received mails are "Email not trusted".
`if (not mailfrom.endswith("@mydomain.com") or 
     not mailfrom.endswith("@mydomain2.com")):
        raise Exception("Email not trusted")`

**Comment by geek-at** [comment]
should now work with the latest update
