### ISSUE TITLE
Cant figured how to use MX records for the domain

### ISSUE THREAD

**Issue by nhCoder** [HaschekSolutions/opentrashmail#19]
can you help me set MX records for the domain greenfether.com whats should be the A and MX records with hostname. Someone help me I stuck here

**Comment by geek-at** [comment]
according to a lookup your MX record for greenfether.com is set to "mail.greenfether.com". You should set it to the IP address of the server which is hosting your opentrashmail setup. Then the emails should start coming in

**Comment by nhCoder** [comment]
![Screenshot_2021-03-17-05-23-49-979_com.android.chrome.jpg](https://user-images.githubusercontent.com/29014068/111396488-fd930880-86e0-11eb-9d27-1e8fe5d0918b.jpg)
Its not accepting  IP address of machine in Server input box.. Am i doing it worng.. Any help will be appreciated

**Comment by geek-at** [comment]
Ok if you can't set it directly, you should set this IP as an `A record` for the hostname `mail.greenfether.com` then it should work

**Comment by nhCoder** [comment]
not working with A record also. I set the A record and deployed using commands given but no use.
I suggest there should be a complete guide to deploy like postal or mail in a box.

**Comment by geek-at** [comment]
looks like you have removed your valid entries now. can't find your A record for mail.greenfether.com

It's really easy:

1. set mx record of greenfether.com to `mail.greenfether.com`
2. Set A record of `mail.greenfether.com` to your IPv4 Address

Not sure what you did but neither the MX nor the A record are existing atm

**Comment by nhCoder** [comment]
still not working for me. I m giving you access to my DNS in my hosting please help me configure the MX records.
login at https://login.one.com/cp/
email: qejubi@savageattitude.com
password: Guest.123
vps IP: 143.198.57.75
i m waiting help me

**Comment by nhCoder** [comment]
Hey i have set mx and A records but still not working

**Comment by nhCoder** [comment]
my bad  port 25 was blocked.
its working now
