### ISSUE TITLE
How to disclose a potential security issue?

### ISSUE THREAD

**Issue by zidingz** [HaschekSolutions/opentrashmail#25]
Hey there,

As there isn't a SECURITY.md or contact address in your repository, I am not sure how to contact you regarding a potential security issue.

Would you kindly provide an email so I can send you the details? Else, simply add a SECURITY.md file with an e-mail to your repository. GitHub recommends this as the best way to ensure security issues are responsibly disclosed. Or perhaps I should just email @geek-at directly?

Look forward to hearing from you, thanks!

**Comment by geek-at** [comment]
Hey! You can either send it to me (christian@haschek.at) or office@haschek-solutions.com or just post it as an Issue or directly as a pull request.

**Comment by zidingz** [comment]
Thanks! Will do.
