### ISSUE TITLE
E-Mail not displayed on Webinterface

### ISSUE THREAD

**Issue by byteturtle** [HaschekSolutions/opentrashmail#29]
Steps to reproduce:
1. run using docker as described in readme
2. send e-mail

expected behaviour:
* e-mail gets saved to disk
* e-mail gets displayed on webinterface

actual behaviour:
* e-mail gets saved to disk
* e-mail doesn't get displayed on webinterface

Starting Open Trashmail
From https://github.com/HaschekSolutions/opentrashmail
   6fec905..cc7b184  master     -> origin/master
Updating 6fec905..cc7b184
Fast-forward
 web/api.php | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
 [+] Starting php
 [+] Starting nginx
 [+] Setting up config.ini
   [i] Active Domain(s): mytestdomain.xyz
   [i] Setting up dateformat to: 'D.M.YYYY HH:mm'
 [+] Starting Mailserver
[i] Starting Mailserver on port 25
2021-07-11 15:13:15,569 - __main__ - DEBUG - Receiving message from: 1.2.3.4
2021-07-11 15:13:15,570 - __main__ - DEBUG - Message addressed from: mysender@example.com
2021-07-11 15:13:15,570 - __main__ - DEBUG - Message addressed to: ['cyclone-angora@mytestdomain.xyz']
2021-07-11 15:13:15,578 - __main__ - DEBUG - Subject: Test

Mailserver and Addresses have been replaced by example.com, mytestdomain.xyz and 1.2.3.4

**Comment by skyelights** [comment]
I'm having the same issue, the API keeps responding with `Invalid Email address` no matter what address I use, but no message is displayed in the frontend about that either.

**Comment by skyelights** [comment]
Here's the offending line that always turns the `$email` var into an empty string.
https://github.com/HaschekSolutions/opentrashmail/blob/cc7b18400ade61e91d3b366ff88c252f7e3fe27f/web/api.php#L11-L11

**Comment by Dan-Q** [comment]
Sorry, I reported this in #31 (mine's a dupe). I've put a suggested solution into that issue, which I'm closing now.
