### ISSUE TITLE
Open relay

### ISSUE THREAD

**Issue by webzi** [HaschekSolutions/opentrashmail#3]
When using this, bots are using the mailserver to send out SPAM.

Are there any way you could tell the mailserver, only to accept outgoing connections from localhost?

**Comment by chrisiaut** [comment]
Wow you scared me for a second.

Outgoing mail is **not supported** on the mail script. It _looks_ like spammers are sending because your the server acts like it is sending but it's not. It just stores the data locally and then exits.

I have confirmed this now using tcpdump.
