### ISSUE TITLE
Feature suggestion: optionally delete emails after they reach a certain age?

### ISSUE THREAD

**Issue by Dan-Q** [HaschekSolutions/opentrashmail#33]
I'd like to be able to set an environment variable, e.g. `MAXAGE`, to say how many days old an email should be before it's deleted. An automated job can then delete ones over that age.

(My opentrashmail server gathered multiple gigabytes of junk!)

**Comment by geek-at** [comment]
love the idea, as I'm having the same problems on my public instance. Also should implement all emails to non-configured domains should be discarded

**Comment by Dan-Q** [comment]
In the meantime (for anybody who wants to hack something together on their own box), I've manually added the following script to `/etc/periodic/daily/delete-old-mail` to delete mail older than 7 days:

```sh
#!/bin/sh
find /var/www/opentrashmail/data/* -mtime +7 -delete
```

It's a bit clunky (and will do stupid things like trying to delete directories before it deletes the files within them, but that fixes itself the next day) but it stops the server getting bogged down.
