### ISSUE TITLE
custom settings per address

### ISSUE THREAD

**Issue by geek-at** [HaschekSolutions/opentrashmail#35]
Settings should be overwritable per address.

So i can set cleanup time for a few hours but only on one addres, etc.

Also opens possibilities for configuring forwarding emails to different (real) mailboxes on a per-address basis

**Comment by NgaoDaCoPho** [comment]
![image](https://user-images.githubusercontent.com/87919718/148866798-243068e7-2708-40a1-9c2d-a1f3ce03ddb7.png)
I tried to send message to that mail but I can't
![image](https://user-images.githubusercontent.com/87919718/148866875-bb972532-2397-4d70-8311-722b3f6f3914.png)
I don't know what's wrong
Can you help me pleasse:((((

**Comment by geek-at** [comment]
@NgaoDaCoPho not 100% sure if that's the issue but set the mx record to "namkhanh61.net" without the "mail." 

Also when I look up your mx record it's set to _dc-mx.e620e9ec8e4f.namkhanh61.net.
