### ISSUE TITLE
Deleting emails from web interface fails

### ISSUE THREAD

**Issue by t10ss** [HaschekSolutions/opentrashmail#37]
I suspect it is due to nginx running under nginx user but files being created under root.
What's the fix for that?

**Comment by jackblk** [comment]
I'm checking out the project, I use `docker run -it -p 25:25 -p 80:80 hascheksolutions/opentrashmail` to run the server and I also cannot delete the email. My test email does not have attachment.

**Comment by rlyttle** [comment]
This still seems to be happening on master. The delete API request returns 200, but the web interface displays a popup showing `Error deleting email: Could not delete email. Permission problem?`

API request:
`http://2049ad.com:8082/api.php?a=del&email=<EMAIL>@<DOMAIN>&mid=1652515203418&_=1652515026379`

Response Status code: `200`

Following deleting and clicking OK on the error alert, if I refresh the web page the email has been deleted (but the delete doesn't show in the UI unless I refresh).

**Comment by geek-at** [comment]
Oh man I forgot to return the actual return code of the deletion so even if the file was deleted successfully it would says permission problem. So that should be fixed now @rlyttle

**Comment by rlyttle** [comment]
Many thanks @geek-at !
