### ISSUE TITLE
Admin mailbox does not auto refresh

### ISSUE THREAD

**Issue by poblabs** [HaschekSolutions/opentrashmail#4]
I'm working on a PR for a few bugs I'm seeing, but I wanted to document this one too. When you first open the site and you first access the admin account, the `setInterval(updateEmailTable, 5000)` isn't invoked. Don't know why yet. 

If you load another non-admin account, it works, and if you then go to the admin account, it works because the `setInterval` is already set. 

In some cases, the `setInterval` is set two times.

**Comment by poblabs** [comment]
Oh, I found it: 

```
            if(data.type=="admin")
            {
                clearInterval(timer);
                admin = true;
                $('#tableheader').children(':eq(1)').after('<th scope="col">To</th>');
            }
```

I guess my question is; why are you clearing the interval if the user is admin?

**Comment by chrisiaut** [comment]
The reason is I have a test server that already has a couple hundred emails and the admin user doesn't load very fast (since there is no pagination yet)

I'll keep your edits in the code base and will add pagination soon

**Comment by poblabs** [comment]
Suppose you could add a config.ini option to allow/disallow the ajax reloads on admin page?

**Comment by poblabs** [comment]
Oh actually, looks like an error was in commit https://github.com/HaschekSolutions/opentrashmail/commit/ad8deb45bb430162ec3f06081b56d4da12826bc1 where it commented out the admin page `clearInterval` by mistake. I didn't mean to commit that - but in case you want to back it out
