### ISSUE TITLE
Attached images in HTML preview do not work

### ISSUE THREAD

**Issue by Cyberes** [HaschekSolutions/opentrashmail#41]
Attached images in HTML preview section do not render. Here is an example:

<details>
<summary>Image kinda big</summary>
<br>

![Screenshot from 2022-05-09 12-17-22](https://user-images.githubusercontent.com/64224601/167472112-29c3b941-b69d-4af0-8486-d8fdd6d4a65f.png)

</details>

The images' `src` is always a non-URL. For example:
```
cid:37686D32@F0369F32.19717862.jpg
```

A fix for this issue is to rewrite the `image` tag's `src` in the HTML preview section. `cid:37686D32@F0369F32.19717862.jpg` would become `http://example.com/api.php?a=attachment&email=test@example.com&id=12345&filename=test.jpg`.

Also, `<` and `>` is getting rendered inside the Raw Email section as HTML. These characters need to be escaped.

**Comment by geek-at** [comment]
implemented in v1.1.3
