### ISSUE TITLE
Error starting mailserver

### ISSUE THREAD

**Issue by sutidor** [HaschekSolutions/opentrashmail#43]
I get an error starting mailserver on port 25, even though I chose a different port.
Google says, it is because it is being started as non-privileged user nginx.
`
su - nginx -s /bin/ash -c 'cd /var/www/opentrashmail/python;python mailserver.py'
`

**Comment by geek-at** [comment]
is this via docker or without?

**Comment by KaygorodovIS** [comment]
Startin via docker
```
Starting Open Trashmail
 [+] Starting php
 [+] Starting nginx
 [+] Setting up config.ini
   [i] Using default dateformat
 [+] Starting Mailserver
[i] Starting Mailserver on port 25
Traceback (most recent call last):
  File "mailserver.py", line 173, in <module>
    server = CustomSMTPServer(('0.0.0.0', port), None) # use your public IP here
  File "/usr/lib/python2.7/smtpd.py", line 285, in __init__
    self.bind(localaddr)
  File "/usr/lib/python2.7/asyncore.py", line 342, in bind
    return self.socket.bind(addr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 13] Permission denied
```

**Comment by drahdiwaberl** [comment]
servus,

getting the same as @KaygorodovIS above - but since i'm root and am using `-p 2525:25 -p 8099:80` priveleges shouldn't be an issue, should they?

**Comment by geek-at** [comment]
you're also getting permission denied error inside of python @drahdiwaberl ?
