### ISSUE TITLE
FeatureRequest: TLS-Support, GUI-Improvments, Live-Logging

### ISSUE THREAD

**Issue by Gill-Bates** [HaschekSolutions/opentrashmail#47]
Awesome project! I really love it because more and more trash mail providers end up on [blacklists](https://gist.github.com/michenriksen/8710649).

**Three improvements (a.k.a. Feature Requests):**

- [ ] Adding TLS-Support: https://pypi.org/project/smtpd-tls/
- [x] Add a "[Copy-to-Clipboard](https://www.w3schools.com/howto/howto_js_copy_clipboard.asp)"-Icon for the random generated email address
- [x] When logged in as Admin into the GUI, add a button to tail the maillog inside the browser -> http://websocketd.com/

**Comment by geek-at** [comment]
copy to clipboard now implemented in the new version. for TLS I'll have to look into it
