### ISSUE TITLE
Is it possible to import old mail after a migration?

### ISSUE THREAD

**Issue by manfromafar** [HaschekSolutions/opentrashmail#48]
I've been messing with migrating the install and found that after I move the install to a new server opentrashmail fails to load previous emails. 
It will only display emails up to the point in which it started receiving new emails. 

So if it possible to tell opentrashmail to list old emails that are still on disk in the data dir?

**Comment by geek-at** [comment]
actually it's only file based so if you copy the data directory to your new server it should auotmatically be able to lst all emails.

If you can't see them from the UI or the API, you might have a permission problem
