### ISSUE TITLE
Plan from migrating away from dockerhub?

### ISSUE THREAD

**Issue by hydrargyrum** [HaschekSolutions/opentrashmail#49]
Opentrashmail's docker image is currently hosted on dockerhub, which has released a [new policy that might endanger your hosting there](https://blog.alexellis.io/docker-is-deleting-open-source-images/) ([see also](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/)). Do you have any plans for migrating hosting elsewhere?

**Comment by geek-at** [comment]
Yes I'll be migrating the repos to github soon

**Comment by geek-at** [comment]
fixed in https://github.com/HaschekSolutions/opentrashmail/commit/59b7bdd2b5a50b67b61c42084c81b26c242c6dce

**Comment by hydrargyrum** [comment]
Great! Thanks for the quick action
