### ISSUE TITLE
Admin account returning no emails

### ISSUE THREAD

**Issue by DasDunkel** [HaschekSolutions/opentrashmail#53]
Not sure if I'm misunderstanding the limited docs, but when attempting to set the admin account with the docker image I'm unable to view all emails sent to the server, instead only seeing messages sent to the set address. 
Docker logs confirm that the value has been read with `[i] Set admin to: "admin@domain.tld"`

I have tried setting the `ADMIN` environment variable to different values such as `admin` and `admin@domain.tld` to no success, even attempting addresses that are not on the hosted domain.

**Comment by DasDunkel** [comment]
I believe I have figured out the cause of this issue, if the admin address has any upper case characters, for example using a randomly generated string, it simply will not work, I believe this may be due to the input being forced to lowercase at some stage

**Comment by geek-at** [comment]
also quotation marks error. remove them from the env and it should work
