### ISSUE TITLE
Discard unknown discarding all wildcard domains

### ISSUE THREAD

**Issue by DasDunkel** [HaschekSolutions/opentrashmail#54]
With `DISCARD_UNKNOWN` set to `true` emails sent to an address using a wildcard domain are discarded.

For example;
Domain: `*.domain.tld,domain.tld`
Address: `random.user@rand.domain.tld`
 Log message: `Discarding email for unknown domain: rand.domain.tld`

**Comment by geek-at** [comment]
Cannot reproduce. Did you restart the mailserver after changing the config?

**Comment by DasDunkel** [comment]
Yes, even with the container completely remade it still rejects wildcard domains; screenshot of docker compose file and logs: https://dunk.dev/x2gMWjdMk8h5.png
The address I sent the test email to was randomly generated by the WebUI

**Comment by geek-at** [comment]
probably because of the quotation marks. Check the config.ini that was generated but removing the quotation marks should fix it
