### ISSUE TITLE
Date format value ignored

### ISSUE THREAD

**Issue by DasDunkel** [HaschekSolutions/opentrashmail#55]
Setting the `DATEFORMAT` variable for the container the WebUI displays no changes.

For example;
Date format; `dddd, MMMM Do YYYY, h:mm:ss a`
Expected output; `Wednesday, November 8th 2023, 3:36:17 pm`
Actual output; `2023-11-08T15:36:17+00:00`

**Comment by geek-at** [comment]
I'm currently doing a rewrite on the GUI, I'll make sure it's correctly implemented

**Comment by geek-at** [comment]
should work now with the new update
