### ISSUE TITLE
500 response to API requests

### ISSUE THREAD

**Issue by DasDunkel** [HaschekSolutions/opentrashmail#57]
Requests to the API within the new WebUI, such as viewing/deleting an email, are returning a 500 status code.

Attempting to make an API request to the container's IP directly to rule out the proxy gives the same 500 status code, full log: https://haste.dunk.dev/mf5HrI1KI7NW

The new `URL` value has been set and the container has been recreated multiple times

View errors in the browser's console here https://tmp.totallylegit.link/address/happy.cherry@date.totallylegit.link

**Comment by geek-at** [comment]
just pushed a fix. Used php8 function in php7
