### ISSUE TITLE
Repeated uncaptured exception

### ISSUE THREAD

**Issue by DasDunkel** [HaschekSolutions/opentrashmail#60]
Error is repeated for several emails over and over again, in the UI [no information is shown](https://dunk.dev/PB1oJHpL2OZF.png), however, the file stored seems to be half written

Error;
```
error: uncaptured python exception, closing channel <smtpd.SMTPChannel connected <IP>:4996 at 0x7ff4397f57d0> (<type 'exceptions.UnicodeDecodeError'>:'utf8' codec can't decode byte 0xe0 in position 6753: invalid continuation byte [/usr/lib/python2.7/asyncore.py|read|83] [/usr/lib/python2.7/asyncore.py|handle_read_event|449] [/usr/lib/python2.7/asynchat.py|handle_read|165] [/usr/lib/python2.7/smtpd.py|found_terminator|181] [mailserver.py|process_message|145] [/usr/lib/python2.7/json/__init__.py|dump|189] [/usr/lib/python2.7/json/encoder.py|_iterencode|434] [/usr/lib/python2.7/json/encoder.py|_iterencode_dict|408] [/usr/lib/python2.7/json/encoder.py|_iterencode_dict|390])
error: uncaptured python exception, closing channel <smtpd.SMTPChannel connected <IP>:61516 at 0x7ff4397f57d0> (<type 'exceptions.UnicodeDecodeError'>:'utf8' codec can't decode byte 0xe0 in position 6753: invalid continuation byte [/usr/lib/python2.7/asyncore.py|read|83] [/usr/lib/python2.7/asyncore.py|handle_read_event|449] [/usr/lib/python2.7/asynchat.py|handle_read|165] [/usr/lib/python2.7/smtpd.py|found_terminator|181] [mailserver.py|process_message|145] [/usr/lib/python2.7/json/__init__.py|dump|189] [/usr/lib/python2.7/json/encoder.py|_iterencode|434] [/usr/lib/python2.7/json/encoder.py|_iterencode_dict|408] [/usr/lib/python2.7/json/encoder.py|_iterencode_dict|390])
```

Let me know if you'd like the partial file sent over in private

**Comment by geek-at** [comment]
very strange. this happened when you were sending an attachment? or is the error with the email itself?

**Comment by DasDunkel** [comment]
They appear to be emails from Discord

**Comment by geek-at** [comment]
I just pushed a new version with the env variable `SHOW_LOGS` if set to true will show the logs in the GUI. Can you try to reproduce and show me the mail log?

**Comment by DasDunkel** [comment]
Hi, ever since that update the emails have stopped, I'm not sure if it's because of a change in the update or if they've stopped being sent, I'll try rolling back to a previous release later today to see if the emails start again

**Comment by geek-at** [comment]
you should be able to see in the logs if no emails came or if they were dropped or crashed

**Comment by DasDunkel** [comment]
That's the thing, the logs were empty except the startup stuff, even when I sent mail myself, and upon testing now I'm unable to send any mail to the server, the response being `500 Error: (TypeError) 'NoneType' object is not subscriptable`

**Comment by geek-at** [comment]
try again with 1.1.4 

500 should be gone now

**Comment by DasDunkel** [comment]
No more emails have been received regarding this issue regardless of which version is used, so I believe they are not being sent anymore.

I'll close this issue for the time being and continue running tests to see if I can cause the errors again.
