### ISSUE TITLE
Feature request; option to add random characters to addresses

### ISSUE THREAD

**Issue by DasDunkel** [HaschekSolutions/opentrashmail#61]
It'd be nice to increase the randomness of addresses generated to help reduce the effectiveness of brute-force API checks.

For example, being able to swap a word for a number of random characters in either the username or subdomain if using wildcard domains.

This would make addresses less memorable but it could be recommended that users bookmark the URL to regain access upon generating a new address.

**Comment by geek-at** [comment]
You don't need to use the random button. You can use any address. Since the mail server only looks at the domain and nothing else, email addresses don't have to be "generated" before you can send emails to it. If the subdomain is correct you can use any string as email
