### ISSUE TITLE
500 Error: (TypeError)

### ISSUE THREAD

**Issue by JustMe0815** [HaschekSolutions/opentrashmail#62]
Hi there,

first off, i love this project. I set this one up in no time using docker. Regular emails work fine, but when adding attachments, i am getting:

500 Error: (TypeError)
    'NoneType' object is not subscriptable (in reply to end of DATA command)
    

i am using hascheksolutions/opentrashmail:latest

**Comment by geek-at** [comment]
Ah thank you can confirm, working on it
