### ISSUE TITLE
Digitally signed emails are not decoded

### ISSUE THREAD

**Issue by DasDunkel** [HaschekSolutions/opentrashmail#64]
Emails signed by OpenPGP seem to be encoded as base64, in older versions of OpenTrashMail these messages were decoded by the mail server on arrival, but on the latest version the raw base64 is shown instead.

Check here for multiple examples sent over 2 separate versions with and without digital signing
https://tmp.totallylegit.link/address/testing123@test.totallylegit.link

**Comment by geek-at** [comment]
in version 1.2 it should decode it correctly. What version are you running?

**Comment by DasDunkel** [comment]
I'm using version 1.2.0

**Comment by geek-at** [comment]
oh sorry just realized I didn't push the correctly decoded fix. pushing now
