### ISSUE TITLE
template rss.xml.php

### ISSUE THREAD

**Issue by JustMe0815** [HaschekSolutions/opentrashmail#67]
Hi there,

rss.xml.php needs some fixing.

The view raw email link is not pointing to the actual email.

It should look like this:

`<a href="<?= $url ?>/api/raw/<?= $email ?>/<?= $id ?>">View raw email</a> <br/>`

**Comment by geek-at** [comment]
thx, fixed in [v1.2.6](https://github.com/HaschekSolutions/opentrashmail/tree/v1.2.6)
