### ISSUE TITLE
Consider using moment.js for date formatting

### ISSUE THREAD

**Issue by poblabs** [HaschekSolutions/opentrashmail#7]
I'm in the US, and the date format opentrashmail is using doesn't make sense to me at first glance since we use Month/Day/Year format. 

[moment.js](https://momentjs.com) would be great for this type of date formatting to allow others to use the format they're used to. 

This could be a quick add by using an option inside config.ini to define the [string format](https://momentjs.com/docs/#/parsing/string-format/), then have PHP grab the string format when it loads `$settings`, and adding that to the `$o` array. JavaScript can then grab that string format and format the epoch accordingly. 

I have a working example and can submit a PR if you'd like?

**Edit**: here's the working example: https://github.com/poblabs/opentrashmail/commit/f82d50b56e27fe4df6e07f74a740284d5cbde352

**Comment by chrisiaut** [comment]
sure, send that sweet PR
