### ISSUE TITLE
GUI looks different

### ISSUE THREAD

**Issue by Gill-Bates** [HaschekSolutions/opentrashmail#72]
Why does my GUI looks different to the Screenshot on the Project Main Page? And I don't see any "Show Logs"

![image](https://github.com/HaschekSolutions/opentrashmail/assets/25774289/b4776436-ac90-45a4-8cb2-c65055e29c11)

**Comment by Gill-Bates** [comment]
The env `"SHOW_LOGS=true"`  is undocumented :-(

**Comment by JustMe0815** [comment]
I think you can just change the css. The guys over at [https://www.virtualmail.contact/](https://www.virtualmail.contact/) did use bootstrap

**Comment by geek-at** [comment]
I think @Gill-Bates means that I forgot to update the screenshots after updating the UI. Will do soon 😁
