### ISSUE TITLE
/run/nginx folder missing on k8s

### ISSUE THREAD

**Issue by tctlrd** [HaschekSolutions/opentrashmail#74]
For some reason the /run/nginx folder is missing when I deploy opentrashmail on kubernetes.
This prevents nginx from starting.
nginx throws this error: "nginx: [emerg] open() "/run/nginx/nginx.pid" failed (2: No such file or directory)"
I realize that there is a command to create this folder in the Dockerfile. I am not sure why it is missing whenever I deploy...
I was able to solve the issue by adding "mkdir -p /run/nginx" to the start.sh before the "nginx" command.
https://github.com/tctlrd/opentrashmail/blob/master/docker/rootfs/start.sh#L22
If this fix could be added, that would be nice.

**Comment by geek-at** [comment]
sure, send a pull request
