### ISSUE TITLE
Unable to copy mail address

### ISSUE THREAD

**Issue by borekon** [HaschekSolutions/opentrashmail#77]
When clicking on _copy address to clipboard__ an error shows in browser's console:
![image](https://github.com/HaschekSolutions/opentrashmail/assets/9289539/bbad9826-8dd8-4a27-8813-13e80897c6cf)

**Comment by geek-at** [comment]
Strange, can you tell me the following things:

- Which Borwser are you using
- Which version of OpenTrashmail are you running?

**Comment by borekon** [comment]
I'm using version 1 according to docker-compose file.
Tried with Edge and Brave (both Chromium-based)

**Comment by geek-at** [comment]
cannot reproduce even with the same browsers. Maybe a plugin on your end?
